Repository CycloneDX/specification, pull requests merged in 2023-06, with the labels that each got.

#234 Fixing missing data governance on service data
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  tools/src/test/resources/1.5/valid-saasbom-1.5.json
  tools/src/test/resources/1.5/valid-saasbom-1.5.textproto
  tools/src/test/resources/1.5/valid-saasbom-1.5.xml
Labels: defect

#227 Added poam as external reference type
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
Labels: proposed core enhancement, RFC vote accepted

#228 Added bom-refs to organizationalEntity and organizationalContact
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  tools/src/test/resources/1.5/valid-metadata-manufacture-1.5.json
  tools/src/test/resources/1.5/valid-metadata-manufacture-1.5.textproto
  tools/src/test/resources/1.5/valid-metadata-manufacture-1.5.xml
  tools/src/test/resources/1.5/valid-metadata-supplier-1.5.json
  tools/src/test/resources/1.5/valid-metadata-supplier-1.5.textproto
  tools/src/test/resources/1.5/valid-metadata-supplier-1.5.xml
Labels: proposed core enhancement, request for comment, RFC vote accepted

#224 Add SSVC to existing rating methods
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
Labels: proposed core enhancement, request for comment, RFC notice sent, RFC vote accepted

#222 Added formulation support and test cases
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  tools/src/test/resources/1.5/valid-formulation-1.5.json
  tools/src/test/resources/1.5/valid-formulation-1.5.textproto
  tools/src/test/resources/1.5/valid-formulation-1.5.xml
Labels: proposed core enhancement, request for comment, RFC notice sent, RFC vote accepted

#258 V1.5 JSON: fix `oneOf` documentations
  docgen/json/.gitignore
  docgen/xml/.gitignore
  schema/bom-1.5.schema.json
Labels: defect, documentation

#253 streamline VulnerabilityReference
  schema/bom-1.5.proto
  schema/bom-1.5.xsd
Labels: defect

#260 adjust default values
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
Labels: defect
