Repository CycloneDX/specification, pull requests merged in 2023-05, with the labels that each got.

#219 fix `vulnerability.affects[].versions[].range` ref
  schema/bom-1.4.schema.json
Labels: defect

#218 fix `vulnerability.affects[].versions[].range` ref
  schema/bom-1.5.schema.json
Labels: defect

#209 Added support for ML
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  tools/src/test/resources/1.5/valid-machine-learning-1.5.json
  tools/src/test/resources/1.5/valid-machine-learning-1.5.textproto
  tools/src/test/resources/1.5/valid-machine-learning-1.5.xml
Labels: proposed core enhancement, request for comment, RFC notice sent, RFC vote accepted

#221 hint for device properties
  schema/bom-1.3.proto
  schema/bom-1.3.xsd
  schema/bom-1.4.proto
  schema/bom-1.4.schema.json
  schema/bom-1.4.xsd
Labels: documentation

#220 hint for device properties
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
Labels: documentation

#212 Added additional compositions and identity
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  tools/src/test/resources/1.5/valid-compositions-1.5.json
  tools/src/test/resources/1.5/valid-compositions-1.5.textproto
  tools/src/test/resources/1.5/valid-compositions-1.5.xml
Labels: proposed core enhancement, request for comment, RFC notice sent, RFC vote accepted

#213 Added lifecycle support
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  tools/src/test/resources/1.5/valid-metadata-lifecycle-1.5.json
  tools/src/test/resources/1.5/valid-metadata-lifecycle-1.5.textproto
  tools/src/test/resources/1.5/valid-metadata-lifecycle-1.5.xml
Labels: proposed core enhancement, request for comment, RFC notice sent, RFC vote accepted

#215 Adding external reference support for adversary model and risk assessment
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
Labels: proposed core enhancement, request for comment, RFC notice sent, RFC vote accepted

#230 fix JSON schema issues found by AJV
  .github/workflows/js.yml
  schema/bom-1.5.schema.json
  schema/jsf-0.82.schema.json
  tools/src/test/js/.gitignore
  tools/src/test/js/README.md
  tools/src/test/js/json-schema-lint-tests.js
  tools/src/test/js/package.json
Labels: defect

#205 `licenseChoice` streamlined
  schema/bom-1.5.schema.json
Labels: defect
