Repository CycloneDX/specification, pull requests merged in 2024-03, with the labels that each got.

#385 introduce QA pipeline for protobuf schemas
  .github/dependabot.yml
  .github/workflows/test_proto.yml
  schema/bom-1.6.proto
  tools/src/test/proto-test.sh
  tools/src/test/proto/buf_breaking-remote.yaml
  tools/src/test/proto/buf_breaking-version.yaml
  tools/src/test/proto/buf_lint.yaml
  tools/src/test/proto/test.sh
  tools/src/test/resources/1.4/valid-release-notes-1.4.textproto
  tools/src/test/resources/1.5/valid-release-notes-1.5.textproto
  tools/src/test/resources/1.6/valid-release-notes-1.6.textproto
Labels: ready for review, test-data, chore: QA, format: ProtoBuf

#389 tests: add example for component scope
  tools/src/test/resources/1.6/valid-bom-1.6.json
  tools/src/test/resources/1.6/valid-bom-1.6.textproto
Labels: ready for review, test-data

#397 docs: spelling and grammar checks
  schema/bom-1.6.proto
Labels: documentation

#398 docs: Spelling and grammar checks
  schema/bom-1.6.schema.json
Labels: documentation

#403 remove restriction on json's `$schema` annotation
  schema/bom-1.6.schema.json
Labels: ready for review, format: JSON

#401 fix: protobuf `Metadata.licenses` repeated
  schema/bom-1.6.proto
  tools/src/test/resources/1.6/valid-metadata-license-1.6.json
  tools/src/test/resources/1.6/valid-metadata-license-1.6.textproto
  tools/src/test/resources/1.6/valid-metadata-license-1.6.xml
Labels: defect, ready for review, format: ProtoBuf

#415 docs: fix examples for `versionRange` according to VERS spec
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: defect, documentation

#416 Added descriptions for ML learning types
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: documentation

#418 1.6 bump bufbuild buf 1.30.0
  tools/src/test/proto/test.sh
Labels: dependencies, chore: QA

#417 fix/harmonize version length
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: defect

#412 Added support for concluded value. Updated test cases.
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/valid-evidence-1.6.json
  tools/src/test/resources/1.6/valid-evidence-1.6.textproto
  tools/src/test/resources/1.6/valid-evidence-1.6.xml
Labels: proposed core enhancement, promote to tc54, tc54 reviewed, tc54 accepted

#408 Added support for license acknowledgements
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/valid-license-expression-1.6.json
  tools/src/test/resources/1.6/valid-license-expression-1.6.textproto
  tools/src/test/resources/1.6/valid-license-expression-1.6.xml
  tools/src/test/resources/1.6/valid-license-id-1.6.json
  tools/src/test/resources/1.6/valid-license-id-1.6.textproto
  tools/src/test/resources/1.6/valid-license-id-1.6.xml
Labels: proposed core enhancement, promote to tc54, tc54 reviewed, tc54 accepted

#395 Propose new environmental consideration information for ML models
  .gitignore
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/valid-machine-learning-considerations-env-1.6.json
  tools/src/test/resources/1.6/valid-machine-learning-considerations-env-1.6.textproto
  tools/src/test/resources/1.6/valid-machine-learning-considerations-env-1.6.xml
Labels: proposed core enhancement, request for comment, ready for review, promote to tc54, tc54 reviewed, tc54 accepted

#414 Add support for OmniBOR and Software Heritage persistent IDs
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/valid-component-identifiers-1.6.json
  tools/src/test/resources/1.6/valid-component-identifiers-1.6.textproto
  tools/src/test/resources/1.6/valid-component-identifiers-1.6.xml
Labels: proposed core enhancement, promote to tc54, tc54 reviewed, tc54 accepted
