Repository CycloneDX/specification, pull requests merged in 2024-02, with the labels that each got.

#369 docs: Tweak "compliment" to "complement"
  README.md
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: documentation

#292 fix #288
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/invalid-license-missing-id-and-name-1.6.json
  tools/src/test/resources/1.6/invalid-license-missing-id-and-name-1.6.textproto
  tools/src/test/resources/1.6/invalid-license-missing-id-and-name-1.6.xml
Labels: defect, ready for review

#375 1.6 dev fix properties json - fixes #371
  schema/bom-1.6.schema.json
  tools/src/test/resources/1.6/invalid-properties-1.6.json
  tools/src/test/resources/1.6/invalid-properties-1.6.textproto
  tools/src/test/resources/1.6/invalid-properties-1.6.xml
  tools/src/test/resources/1.6/valid-properties-1.6.json
  tools/src/test/resources/1.6/valid-properties-1.6.textproto
  tools/src/test/resources/1.6/valid-properties-1.6.xml
Labels: defect

#374 fix: correcting title of `attestations[].map[].counterClaim`
  schema/bom-1.6.schema.json
Labels: documentation

#377 Add `meta:enum` descriptions for task types
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: ready for review, documentation

#378 docs: describe `$.metadata.licenses`
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: ready for review, documentation

#381 feat: external reference type for RFC-9116
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: proposed core enhancement, ready for review, RFC vote accepted, promote to tc54, tc54 reviewed, tc54 accepted
