Repository CycloneDX/specification, pull requests merged in 2024-06, with the labels that each got.

#451 Fix(1.6spec): Fixed typo in componentEvidence description
  schema/bom-1.6.schema.json
Labels: ready for review, documentation, schema 1.6

#475 issue451-streamline
  schema/bom-1.6.xsd
Labels: documentation, schema 1.6

#480 tests: Update to cyclonedx-core-java-9.0.2 for test runners
  tools/pom.xml
  tools/src/test/java/org/cyclonedx/schema/JsonSchemaVerificationTest.java
  tools/src/test/java/org/cyclonedx/schema/XmlSchemaVerificationTest.java
Labels: ready for review, chore: QA

#482 tests: Adding 1.6 valid and invalid test files in the Java tests
  tools/src/test/java/org/cyclonedx/schema/BaseSchemaVerificationTest.java
  tools/src/test/java/org/cyclonedx/schema/JsonSchemaVerificationTest.java
  tools/src/test/java/org/cyclonedx/schema/XmlSchemaVerificationTest.java
Labels: chore: QA

#489 Update pom.xml
  tools/pom.xml
Labels: dependencies

#490 docs: revisit example urls in spec 1.6
  schema/bom-1.6.xsd
Labels: documentation
