Repository CycloneDX/specification, pull requests merged in 2024-01, with the labels that each got.

#362 Refactored JSON enum descriptions to use meta:enum
  schema/bom-1.6.schema.json
  tools/src/test/js/json-schema-lint-tests.js
Labels: documentation

#269 Add `source-distribution` element to `externalReferenceType`
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: proposed core enhancement, promote to tc54, tc54 reviewed, tc54 accepted

#348 1.6 dev attestations
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/valid-attestation-1.6.json
  tools/src/test/resources/1.6/valid-attestation-1.6.textproto
  tools/src/test/resources/1.6/valid-attestation-1.6.xml
  tools/src/test/resources/1.6/valid-standard-1.6.json
  tools/src/test/resources/1.6/valid-standard-1.6.textproto
  tools/src/test/resources/1.6/valid-standard-1.6.xml
Labels: tc54 reviewed, tc54 accepted

#359 Fixed evidence identity. Updated test cases
  docgen/json/templates/cyclonedx/tabbed_section.html
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/js/json-schema-lint-tests.js
  tools/src/test/resources/1.6/valid-evidence-1.6.json
  tools/src/test/resources/1.6/valid-evidence-1.6.textproto
  tools/src/test/resources/1.6/valid-evidence-1.6.xml
Labels: defect

#347 1.6 dev cbom
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
  tools/src/test/resources/1.6/valid-cryptography-full-1.6.json
  tools/src/test/resources/1.6/valid-cryptography-full-1.6.textproto
  tools/src/test/resources/1.6/valid-cryptography-full-1.6.xml
  tools/src/test/resources/1.6/valid-cryptography-implementation-1.6.json
  tools/src/test/resources/1.6/valid-cryptography-implementation-1.6.textproto
  tools/src/test/resources/1.6/valid-cryptography-implementation-1.6.xml
Labels: proposed core enhancement, promote to tc54, tc54 reviewed, tc54 accepted
