Repository CycloneDX/specification, pull requests merged in 2025-02, with the labels that each got.

#479 feat(DX): add xml catalog for XSD
  schema/xmlcatalog.xml
  tools/pom.xml
  tools/src/test/java/org/cyclonedx/schema/XmlCatalogVerificationTest.java
Labels: ready for review, format: XML

#581 fix: version range spec url
  schema/bom-1.4.proto
  schema/bom-1.4.schema.json
  schema/bom-1.4.xsd
  schema/bom-1.5.proto
  schema/bom-1.5.schema.json
  schema/bom-1.5.xsd
  schema/bom-1.6.proto
  schema/bom-1.6.schema.json
  schema/bom-1.6.xsd
Labels: defect, ready for review, documentation

#588 chore: bump tools buf 1.50.0
  tools/src/test/proto/test.sh
Labels: dependencies

#589 chore: test protobuf acknowledged BC
  tools/src/test/proto/buf_breaking-version.yaml
  tools/src/test/proto/test.sh
Labels: chore: QA

#594 tests: php QA tests run offline
  tools/src/test/php/json-schema-functional-tests.php
  tools/src/test/php/xml-schema-functional-tests.php
Labels: test-data, chore: QA

#592 tests(Java): run test against actual schema files
  tools/pom.xml
  tools/src/test/java/org/cyclonedx/schema/BaseSchemaVerificationTest.java
  tools/src/test/java/org/cyclonedx/schema/JsonSchemaVerificationTest.java
  tools/src/test/java/org/cyclonedx/schema/XmlSchemaVerificationTest.java
Labels: test-data, chore: QA

#601 Fix missing type definitions for ComponentData subelements in XML
  schema/bom-1.7.xsd
Labels: defect, format: XML
